### ISSUE TITLE
cannot find file 

### ISSUE THREAD

**Issue by dmuck** [dm-korottsev/rosreestr-land-parcel-xml-converter#2]
I have downloaded the .xml file from the website (see here: http://rosreestr.ru/wps/portal/cc_ib_opendata2?param_infoblock_document_path=pkk_metadannie.htm), but I get an error after running main.py because it cannot find the file in my directory. 

Any assistance?

**Comment by dm-korottsev** [comment]
Please send me the "log.txt" and other information about the error. I can't figure out what the problem is yet. korotsev_dmitri@mail.ru

**Comment by dmuck** [comment]
13.02.2020  17:11:19 Traceback (most recent call last):
13.02.2020  17:11:19   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:11:19     result = func(arg)
13.02.2020  17:11:19   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 234, in start_conv
13.02.2020  17:11:19     starting_xmlfiles = list(filter(lambda x: x.endswith('.xml'), os.listdir(directory)))
13.02.2020  17:11:19 FileNotFoundError: [Errno 2] No such file or directory: ''
---------------------------------------------------------------------------------------------13.02.2020  17:13:02 Traceback (most recent call last):
13.02.2020  17:13:02   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:13:02     result = func(arg)
13.02.2020  17:13:02   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 234, in start_conv
13.02.2020  17:13:02     starting_xmlfiles = list(filter(lambda x: x.endswith('.xml'), os.listdir(directory)))
13.02.2020  17:13:02 FileNotFoundError: [Errno 2] No such file or directory: ''
---------------------------------------------------------------------------------------------13.02.2020  17:13:03 Traceback (most recent call last):
13.02.2020  17:13:03   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:13:03     result = func(arg)
13.02.2020  17:13:03   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 234, in start_conv
13.02.2020  17:13:03     starting_xmlfiles = list(filter(lambda x: x.endswith('.xml'), os.listdir(directory)))
13.02.2020  17:13:03 FileNotFoundError: [Errno 2] No such file or directory: ''
---------------------------------------------------------------------------------------------13.02.2020  17:13:03 Traceback (most recent call last):
13.02.2020  17:13:03   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:13:03     result = func(arg)
13.02.2020  17:13:03   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 234, in start_conv
13.02.2020  17:13:03     starting_xmlfiles = list(filter(lambda x: x.endswith('.xml'), os.listdir(directory)))
13.02.2020  17:13:03 FileNotFoundError: [Errno 2] No such file or directory: ''
---------------------------------------------------------------------------------------------13.02.2020  17:13:05 Traceback (most recent call last):
13.02.2020  17:13:05   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:13:05     result = func(arg)
13.02.2020  17:13:05   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 234, in start_conv
13.02.2020  17:13:05     starting_xmlfiles = list(filter(lambda x: x.endswith('.xml'), os.listdir(directory)))
13.02.2020  17:13:05 FileNotFoundError: [Errno 2] No such file or directory: ''
---------------------------------------------------------------------------------------------13.02.2020  17:16:28 Traceback (most recent call last):
13.02.2020  17:16:28   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:16:28     result = func(arg)
13.02.2020  17:16:28   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:16:28     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:16:28   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:16:28     tree = ElT.parse(xml_file_path)
13.02.2020  17:16:28   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:16:28     tree.parse(source, parser)
13.02.2020  17:16:28   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:16:28     source = open(source, "rb")
13.02.2020  17:16:28 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:16:28 Traceback (most recent call last):
13.02.2020  17:16:28   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:16:28     result = func(arg)
13.02.2020  17:16:28   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:16:28     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:16:28   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:16:28     tree = ElT.parse(xml_file_path)
13.02.2020  17:16:28   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:16:28     tree.parse(source, parser)
13.02.2020  17:16:28   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:16:28     source = open(source, "rb")
13.02.2020  17:16:28 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:16:32 Traceback (most recent call last):
13.02.2020  17:16:32   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:16:32     result = func(arg)
13.02.2020  17:16:32   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:16:32     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:16:32   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:16:32     tree = ElT.parse(xml_file_path)
13.02.2020  17:16:32   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:16:32     tree.parse(source, parser)
13.02.2020  17:16:32   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:16:32     source = open(source, "rb")
13.02.2020  17:16:32 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:16:32 Traceback (most recent call last):
13.02.2020  17:16:32   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:16:32     result = func(arg)
13.02.2020  17:16:32   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:16:32     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:16:32   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:16:32     tree = ElT.parse(xml_file_path)
13.02.2020  17:16:32   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:16:32     tree.parse(source, parser)
13.02.2020  17:16:32   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:16:32     source = open(source, "rb")
13.02.2020  17:16:32 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:16:50 Traceback (most recent call last):
13.02.2020  17:16:50   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:16:50     result = func(arg)
13.02.2020  17:16:50   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:16:50     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:16:50   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:16:50     tree = ElT.parse(xml_file_path)
13.02.2020  17:16:50   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:16:50     tree.parse(source, parser)
13.02.2020  17:16:50   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:16:50     source = open(source, "rb")
13.02.2020  17:16:50 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:16:50 Traceback (most recent call last):
13.02.2020  17:16:50   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:16:50     result = func(arg)
13.02.2020  17:16:50   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:16:50     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:16:50   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:16:50     tree = ElT.parse(xml_file_path)
13.02.2020  17:16:50   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:16:50     tree.parse(source, parser)
13.02.2020  17:16:50   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:16:50     source = open(source, "rb")
13.02.2020  17:16:50 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:19:10 Traceback (most recent call last):
13.02.2020  17:19:10   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:19:10     result = func(arg)
13.02.2020  17:19:10   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:19:10     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:19:10   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:19:10     tree = ElT.parse(xml_file_path)
13.02.2020  17:19:10   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:19:10     tree.parse(source, parser)
13.02.2020  17:19:10   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:19:10     source = open(source, "rb")
13.02.2020  17:19:10 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:19:10 Traceback (most recent call last):
13.02.2020  17:19:10   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:19:10     result = func(arg)
13.02.2020  17:19:10   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:19:10     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:19:10   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:19:10     tree = ElT.parse(xml_file_path)
13.02.2020  17:19:10   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:19:10     tree.parse(source, parser)
13.02.2020  17:19:10   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:19:10     source = open(source, "rb")
13.02.2020  17:19:10 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:19:46 Traceback (most recent call last):
13.02.2020  17:19:46   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:19:46     result = func(arg)
13.02.2020  17:19:46   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:19:46     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:19:46   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:19:46     tree = ElT.parse(xml_file_path)
13.02.2020  17:19:46   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:19:46     tree.parse(source, parser)
13.02.2020  17:19:46   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:19:46     source = open(source, "rb")
13.02.2020  17:19:46 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:19:46 Traceback (most recent call last):
13.02.2020  17:19:46   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:19:46     result = func(arg)
13.02.2020  17:19:46   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:19:46     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:19:46   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:19:46     tree = ElT.parse(xml_file_path)
13.02.2020  17:19:46   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:19:46     tree.parse(source, parser)
13.02.2020  17:19:46   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:19:46     source = open(source, "rb")
13.02.2020  17:19:46 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Desktop/1701_pkk_metadata\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:23:09 Traceback (most recent call last):
13.02.2020  17:23:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:23:09     result = func(arg)
13.02.2020  17:23:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:23:09     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:23:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:23:09     tree = ElT.parse(xml_file_path)
13.02.2020  17:23:09   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:23:09     tree.parse(source, parser)
13.02.2020  17:23:09   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:23:09     source = open(source, "rb")
13.02.2020  17:23:09 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:23:09 Traceback (most recent call last):
13.02.2020  17:23:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:23:09     result = func(arg)
13.02.2020  17:23:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:23:09     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:23:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:23:09     tree = ElT.parse(xml_file_path)
13.02.2020  17:23:09   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:23:09     tree.parse(source, parser)
13.02.2020  17:23:09   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:23:09     source = open(source, "rb")
13.02.2020  17:23:09 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:24:48 Traceback (most recent call last):
13.02.2020  17:24:48   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:24:48     result = func(arg)
13.02.2020  17:24:48   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:24:48     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:24:48   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:24:48     tree = ElT.parse(xml_file_path)
13.02.2020  17:24:48   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:24:48     tree.parse(source, parser)
13.02.2020  17:24:48   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:24:48     source = open(source, "rb")
13.02.2020  17:24:48 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:24:48 Traceback (most recent call last):
13.02.2020  17:24:48   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:24:48     result = func(arg)
13.02.2020  17:24:48   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:24:48     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:24:48   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:24:48     tree = ElT.parse(xml_file_path)
13.02.2020  17:24:48   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:24:48     tree.parse(source, parser)
13.02.2020  17:24:48   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:24:48     source = open(source, "rb")
13.02.2020  17:24:48 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:31:09 Traceback (most recent call last):
13.02.2020  17:31:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:31:09     result = func(arg)
13.02.2020  17:31:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:31:09     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:31:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:31:09     tree = ElT.parse(xml_file_path)
13.02.2020  17:31:09   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:31:09     tree.parse(source, parser)
13.02.2020  17:31:09   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:31:09     source = open(source, "rb")
13.02.2020  17:31:09 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:31:09 Traceback (most recent call last):
13.02.2020  17:31:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:31:09     result = func(arg)
13.02.2020  17:31:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:31:09     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:31:09   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:31:09     tree = ElT.parse(xml_file_path)
13.02.2020  17:31:09   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:31:09     tree.parse(source, parser)
13.02.2020  17:31:09   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:31:09     source = open(source, "rb")
13.02.2020  17:31:09 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:31:13 Traceback (most recent call last):
13.02.2020  17:31:13   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:31:13     result = func(arg)
13.02.2020  17:31:13   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:31:13     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:31:13   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:31:13     tree = ElT.parse(xml_file_path)
13.02.2020  17:31:13   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:31:13     tree.parse(source, parser)
13.02.2020  17:31:13   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:31:13     source = open(source, "rb")
13.02.2020  17:31:13 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:31:13 Traceback (most recent call last):
13.02.2020  17:31:13   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:31:13     result = func(arg)
13.02.2020  17:31:13   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:31:13     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:31:13   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:31:13     tree = ElT.parse(xml_file_path)
13.02.2020  17:31:13   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:31:13     tree.parse(source, parser)
13.02.2020  17:31:13   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:31:13     source = open(source, "rb")
13.02.2020  17:31:13 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:31:21 Traceback (most recent call last):
13.02.2020  17:31:21   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:31:21     result = func(arg)
13.02.2020  17:31:21   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 195, in rename_xml
13.02.2020  17:31:21     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:31:21   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:31:21     tree = ElT.parse(xml_file_path)
13.02.2020  17:31:21   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:31:21     tree.parse(source, parser)
13.02.2020  17:31:21   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:31:21     source = open(source, "rb")
13.02.2020  17:31:21 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------13.02.2020  17:31:21 Traceback (most recent call last):
13.02.2020  17:31:21   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 37, in wrapped
13.02.2020  17:31:21     result = func(arg)
13.02.2020  17:31:21   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/main.py", line 347, in start_conv
13.02.2020  17:31:21     parcel = AbstractParcel.create_a_parcel_object(xml_file_path)
13.02.2020  17:31:21   File "/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master/parcel.py", line 39, in create_a_parcel_object
13.02.2020  17:31:21     tree = ElT.parse(xml_file_path)
13.02.2020  17:31:21   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
13.02.2020  17:31:21     tree.parse(source, parser)
13.02.2020  17:31:21   File "/opt/anaconda3/lib/python3.7/xml/etree/ElementTree.py", line 587, in parse
13.02.2020  17:31:21     source = open(source, "rb")
13.02.2020  17:31:21 FileNotFoundError: [Errno 2] No such file or directory: '/Users/dmuck/Dropbox/rosreestr-land-parcel-xml-converter-master\\pkk5_meta.xml'
---------------------------------------------------------------------------------------------

**Comment by dm-korottsev** [comment]
To make the program work, you need to save it to a separate folder on your computer's hard disk. For example, C:\, D:\ , etc. The file " pkk5_meta.xml" is not supported because its XML Schema does not match the supported ones. This program processes documents in electronic form (XML) - statements for land plots issued by Rosreestr for a fee. Thank you for your interest!

**Comment by dm-korottsev** [comment]
What data did you want to find on the Rosreestr website? If this is in the open data, I can help you. korotsev_dmitri@mail.ru

**Comment by dmuck** [comment]
I downloaded the metadata from the open data page (see https://rosreestr.ru/wps/portal/cc_ib_opendata, #17).  Basically I want to extract information about every land plot across the country from the Public Cadastre Map.  I am a novice with geospatial data, so I am not really sure where I could find a shape file for the map. I also found this  from the information tab in the Map, but I am not sure whether these files have the relevant information (see here: https://pkk5.rosreestr.ru/arcgis/rest/services/Cadastre).

Please let me know if it is clear what I want to do. Thanks for your help!



On Feb 14, 2020, at 08:05, dm-korottsev <notifications@github.com<mailto:notifications@github.com>> wrote:

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


What data did you want to find on the Rosreestr website? If this is in the open data, I can help you. korotsev_dmitri@mail.ru<mailto:korotsev_dmitri@mail.ru>

**Comment by dm-korottsev** [comment]
Now the site of Federal registration service does not provide this information. You can download this data for 2017 in CSV format (you can open it in QGIS) on this web page https://terraingis.ru/konvertirovaniye-otkrytykh-dannykh-kadastrovoy-karty.html (you need to register and log in first)

**Comment by dmuck** [comment]
Thank you for your help!


On Feb 14, 2020, at 09:33, dm-korottsev <notifications@github.com<mailto:notifications@github.com>> wrote:

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


Now the site of Federal registration service does not provide this information. You can download this data for 2017 in CSV format (you can open it in QGIS) on this web page https://terraingis.ru/konvertirovaniye-otkrytykh-dannykh-kadastrovoy-karty.html (you need to register and log in first)
